Home_work_5/myapp/app.py
from flask import Flask, request, render_template

from views import todo_app

app = Flask(__name__)
app.register_blueprint(todo_app, url_prefix="/todolist")


@app.route("/", methods=["GET", "POST"])
def index():
    return render_template("index.html", name='MAIN PAGE')

Home_work_5/myapp/main.py
from app import app

app.config.update(
    DEBUG=True,
)

if __name__ == "__main__":
    app.run(debug=True)

Home_work_5/myapp/views/__init__.py
from .todolist import todo_app

Home_work_5/myapp/views/todolist.py
from flask import Blueprint, render_template, request, jsonify
from werkzeug.exceptions import BadRequest

from dataclasses import dataclass

todo_app = Blueprint("product_app", __name__)

@dataclass
class Task:
    name: str
    isDone: bool
    # priority: int

    def update_status(self, isdone:bool):
        self.isDone = isdone


TASKS = {
    1: Task('Clean a home', False),
    2: Task('Learn Python', False),
    3: Task('Buy purchase', True)
}

SEQ = len(TASKS)


@todo_app.route("/", methods=['GET', 'POST'])
def product_list():
    global SEQ
    if request.method == 'POST':
        print(request.form['data'])
        SEQ += 1
        req_data = request.form['data']
        TASKS[SEQ] = Task(req_data, False)
    return render_template("todolist/index.html", tasks=TASKS)


@todo_app.route("/<int:task_id>/", methods=['GET','DELETE', 'POST'])
def task_detail(task_id: int):
    try:
        task_name = TASKS[task_id]
    except KeyError:
        raise BadRequest(f"Invalid product id #{task_id}")

    if request.method == 'DELETE':
        TASKS.pop(task_id)
        return jsonify(ok=True)

    if request.method == 'POST':
        isDone = True if request.form['isDone'] == '1' else False
        print('isDone=', isDone)
        TASKS[task_id].update_status(isDone)
        print(TASKS[task_id])

    return TASKS[task_id].name

Home_work_5/myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <title>
    {% block title %}
      Base title
    {% endblock %}
  </title>
</head>
<body>
<div class="container">

<nav class="mb-2 navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{{ url_for('index') }}">MySite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('product_app.product_list') }}">Products</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Cart</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Action
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item disabled" href="#">Personal area</a>
          <a class="dropdown-item disabled" href="#">Support</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Logout</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

  {% block body %}
    Base page
  {% endblock %}
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
        crossorigin="anonymous"></script>

{% block after_body %}
{% endblock %}
</body>
</html>

Home_work_5/myapp/templates/index.html
{% extends 'base.html' %}

{% block title %}
  Hello
{% endblock %}

{% block body %}
  <h1>{{ name }}!</h1>
{% endblock %}

Home_work_5/myapp/templates/todolist/index.html
{% extends 'base.html' %}
<style>
  input[type=checkbox]:checked {
    text-decoration: line-through;
  }
</style>

{% block title -%}
  Task list
{%- endblock %}

{% block body %}
  <h1>Task list</h1>
  <div class="alert alert-info" role="alert">
    You have a <b> {{tasks|length}} </b> undone tasks! Let's go!
  </div>
  <div class="row">
    <div class="col-md-12">
      <form>
           <div class="input-group">
            <input type="text" id="new-item" placeholder="Enter a new item" class="form-control">
            <button id="add-btn" type="button" class="btn btn-success">add</button>
        </div>
      </form>
      <ul class="list-group">
        {% for tasks_id in tasks %}
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <div>
              <input type="checkbox" class="chkbox" id="chk-task{{tasks_id}}" name="task{{tasks_id}}" num="{{tasks_id}}" {% if tasks[tasks_id].isDone %} checked {% endif %}>
              <label for="task{{tasks_id}}" {% if tasks[tasks_id].isDone %} style="text-decoration: line-through; color: gray;" {% endif %}>{{ tasks[tasks_id].name }}</label>
            </div>
            <button type="button" class="btn btn-danger btn-sm" id="btn-del-{{tasks_id}}" num="{{tasks_id}}">Delete</button>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>

{% endblock %}

{% block after_body %}
  <script>
    $(document).ready(function() {
    $('#new-item').keypress(function(event) {
      if (event.keyCode == 13) {
        event.preventDefault();
        $('#add-btn').click();
      }
    });
  });

    $(function() {
      $('#add-btn').click(function () {
       $.ajax({
                type: 'POST',
                data: {
                    data : $('#new-item').val()
                },
                success: function(response) {
                    console.log(response);
                }
            })
       $('#new-item').val('');
       location.reload();
      })
    });

  $(function(){
    $('.btn-danger').click(function(){
        var id_task = $(this).attr('num');
        $.ajax({
                url: '/todolist/' + id_task,
                type: 'DELETE',
                success: function(result) {
                    console.log('Успешно удалено!');
                    location.reload();
                }
            });

    });
  });

  $(function(){
    $('.chkbox').click(function(){
        if($(this).prop("checked") == true){
            var id_task = $(this).attr('num');
            $.ajax({
                url: '/todolist/' + id_task,
                type: 'POST',
                data: {
                    isDone : '1'
                },
                success: function(response) {
                    console.log(response);
                    location.reload();
                }
            })
        }
        else if($(this).prop("checked") == false){
            var id_task = $(this).attr('num');
            $.ajax({
                url: '/todolist/' + id_task,
                type: 'POST',
                data: {
                    isDone : '0'
                },
                success: function(response) {
                    console.log(response);
                    location.reload();
                }
            })
        }
    });
});


  </script>
{% endblock %}